name: Test Unit

on:
   push:
    
jobs:
   test:
      runs-on: ubuntu-latest

      steps:
         -  uses: actions/checkout@v1

         - run: npm install -g @devesharp/ds-releaser

         - run: ds-releaser -t semantic --nonRoot