name: Test Unit

on:
   push:
    
jobs:
   test:
      runs-on: ubuntu-latest

      steps:
         -  uses: actions/checkout@v1

         -  name: Use Node.js
            uses: actions/setup-node@v1
            with:
                node-version: '12.x'
                
         - run: npm install -g @devesharp/ds-releaser

         - run: ds-releaser -t semantic --nonRoot